version: '3.9'

services:
  buatsurat-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: buatsurat-backend
    restart: unless-stopped
    working_dir: /var/www/html/buatsurat-backend
    volumes:
      - ./:/var/www/html/buatsurat-backend
    ports:
      - 8001:8001
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    name: shared_network