version: '3.9'

services:
  buatsurat-frontend:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    image: faisalfjri/buatsurat-frontend
    container_name: buatsurat-frontend
    ports:
      - 3001:3001
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    name: shared_network