version: '3.9'

services:
  node:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node
    ports:
      - 3000:3000
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    name: shared_network